# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener:  true
    exception:
        codes:
            App\Exception\ORM\NotFoundException: 404
        messages:
            App\Exception\ORM\NotFoundException: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
